[package]
name = "gameshopui"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.215" }
serde_json = { version = "1.0.133" }
reqwest = "0.12.9"
iced = { version = "0.13.1", features = ["tokio"]}
