[package]
name = "gameshopui"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = "2"
serde = { version = "1.0.215", features = ["serde_derive"] }
serde_json = "1.0.133"
reqwest = "0.12.9"
iced = { version = "0.13.1", features = ["tokio"]}
